### ISSUE TITLE
ImportError: No module named pyexpat

### ISSUE THREAD

**Issue by BarbUk** [trishume/Sublime-Rosetta-Get#1]
I'm using sublime dev build 2169.
Php file in utf8 (linux x86). The language detected is html and i got this error :

``` Html
http://rosettacode.org/mw/api.php?action=query&list=categorymembers&cmtitle=Category:Html&cmlimit=500&format=xml
Traceback (most recent call last):
  File "./sublime_plugin.py", line 327, in run_
  File "./getRosetta.py", line 49, in run
  File "./getRosetta.py", line 34, in getTasksForLang
  File ".\xml\dom\minidom.py", line 1927, in parseString
  File ".\xml\dom\expatbuilder.py", line 32, in <module>
  File ".\xml\parsers\expat.py", line 4, in <module>
ImportError: No module named pyexpat
```

**Comment by trishume** [comment]
I added better bad language detection. I can not reproduce your bug but the latest version should fix it.
